workflows:
  yendo_release:
    name: Yendo Release Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Flutter clean
        script: flutter clean

      - name: Get dependencies
        script: flutter pub get

      - name: Build iOS release (IPA)
        script: |
          flutter build ipa \
            --release \
            --no-tree-shake-icons

    artifacts:
      - build/ios/ipa/*.ipa
