# Plataforma mínima para iOS (requerida por cloud_firestore, firebase_auth, etc.)
platform :ios, '15.0'

# Desactivar estadísticas de CocoaPods
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(
    File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__
  )

  unless File.exist?(generated_xcode_build_settings_path)
    raise "Generated.xcconfig must exist. Run `flutter pub get` first."
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end

  raise "FLUTTER_ROOT not found in Generated.xcconfig. Try deleting Generated.xcconfig, then run `flutter pub get`."
end

require File.expand_path('packages/flutter_tools/bin/podhelper.rb', flutter_root)

# 👇 ESTA LÍNEA ES LA QUE FALTABA ANTES
flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  flutter_post_install(installer)

  # Evitar problemas con simulador arm64
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
